# apps/nginx/overlays/dev/external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nginx-secret        # K8s secret name ArgoCD will create
    creationPolicy: Owner
  data:
  - secretKey: API_KEY        # key in K8s secret
    remoteRef:
      key: gitops/dev/nginx-secret    # AWS secret name
      property: API_KEY               # field in JSON secret
  - secretKey: DB_PASSWORD
    remoteRef:
      key: gitops/dev/nginx-secret
      property: DB_PASSWORD