apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::907615197397:role/external-secrets-role
  name: external-secrets-sa
  namespace: external-secrets
