apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: public.ecr.aws/nginx/nginx
  newTag: "1.25.0"
patches:
- path: replica-patch.yaml