apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: public.ecr.aws/nginx/nginx:1.25.0  # simulating payments app
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 128Mi